package com.ensat.model;
// Generated 16 janv. 2019 15:15:17 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Post generated by hbm2java
 */
@Entity
@Table(name="post"
    ,catalog="atelier"
)
public class Post  implements java.io.Serializable {


     private Integer idPost;
     private Date date;
     private String description;
     private String titre;
     private Integer utilisateurIdUser;
     private Integer idUser;

    public Post() {
    }

    public Post(Date date, String description, String titre, Integer utilisateurIdUser, Integer idUser) {
       this.date = date;
       this.description = description;
       this.titre = titre;
       this.utilisateurIdUser = utilisateurIdUser;
       this.idUser = idUser;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idPost", unique=true, nullable=false)
    public Integer getIdPost() {
        return this.idPost;
    }
    
    public void setIdPost(Integer idPost) {
        this.idPost = idPost;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="titre")
    public String getTitre() {
        return this.titre;
    }
    
    public void setTitre(String titre) {
        this.titre = titre;
    }

    
    @Column(name="utilisateur_idUser")
    public Integer getUtilisateurIdUser() {
        return this.utilisateurIdUser;
    }
    
    public void setUtilisateurIdUser(Integer utilisateurIdUser) {
        this.utilisateurIdUser = utilisateurIdUser;
    }

    
    @Column(name="idUser")
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }




}


